# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9e4c48d4697439dfa8f777304384f228a116785433da81b8d35866299a449ee1586c99862ec65a8ab8e27ff1e92670e94e100b2371a5849a8215a4e6ac6e086

test:
  secret_key_base: 3ea2532a2d54e2e831f9ab815aac84e5ae815f3f4a8b679037327b0244044fcf54c76aa39c2bad5d48ba8d2b335e46b72e3ccf0ff3b4451111969b80da4ebefb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
